const testData = [
	{
		Title: "30 Years and 15 Minutes",
		Year: "2020",
		Rated: "N/A",
		Released: "08 Aug 2020",
		Runtime: "95 min",
		Genre: "Documentary, Animation",
		Director: "Stefan Mandachi",
		Writer: "Stefan Mandachi",
		Actors: "Stefan Mandachi, Cezar Ionascu, Liviu Dragnea, Viorica Dãncilã",
		Plot:
			"Romania is on the last place in Europe in terms of highway kilometers, but on the first place in the number of deaths in road accidents. Entrepreneur Stefan Mandachi builds 1 meter of highway on his private property.",
		Language: "Romanian, English",
		Country: "Romania",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BOTdmODU2ZDQtMDU2MC00ZDkwLTljZjgtY2M3YzZmZWRmMTFjXkEyXkFqcGdeQXVyMTI3NDkxNzM@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.3/10" }],
		Metascore: "N/A",
		imdbRating: "9.3",
		imdbVotes: "43",
		imdbID: "tt12865416",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 345,
		tconst: "tt12865416",
		averageRating: 9.4,
		numVotes: 1923,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Jibon Thekey Neya",
		Year: "1970",
		Rated: "N/A",
		Released: "10 Apr 1970",
		Runtime: "150 min",
		Genre: "Drama, Family, War",
		Director: "Zahir Raihan",
		Writer:
			"Zahir Raihan (story), Amjad Hossain (dialogue), Zahir Raihan (screenplay)",
		Actors: "Abdur Razzak, Suchanda, Shaukat Akbar, Rosy Samad",
		Plot:
			"A political satire of Bangladesh under the rule of Pakistan metaphorically, where an autocratic woman in one family symbolizes the political dictatorship of Ayub Khan in East Pakistan.",
		Language: "Bengali",
		Country: "Bangladesh",
		Awards: "N/A",
		Poster:
			"https://ia.media-imdb.com/images/M/MV5BNTQ4YjUzMWItZjkwYi00NmFkLTg4YTYtYTc0Y2IxZGE0ZDJiXkEyXkFqcGdeQXVyNDI3NjcxMDA@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.3/10" }],
		Metascore: "N/A",
		imdbRating: "9.3",
		imdbVotes: "1,414",
		imdbID: "tt0989831",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 325,
		tconst: "tt0989831",
		averageRating: 9.3,
		numVotes: 1846,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "The Shawshank Redemption",
		Year: "1994",
		Rated: "R",
		Released: "14 Oct 1994",
		Runtime: "142 min",
		Genre: "Drama",
		Director: "Frank Darabont",
		Writer:
			'Stephen King (short story "Rita Hayworth and Shawshank Redemption"), Frank Darabont (screenplay)',
		Actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
		Plot:
			"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
		Language: "English",
		Country: "USA",
		Awards: "Nominated for 7 Oscars. Another 21 wins & 36 nominations.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.3/10" },
			{ Source: "Rotten Tomatoes", Value: "91%" },
			{ Source: "Metacritic", Value: "80/100" },
		],
		Metascore: "80",
		imdbRating: "9.3",
		imdbVotes: "2,321,344",
		imdbID: "tt0111161",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "$28,699,976",
		Production: "Columbia Pictures, Castle Rock Entertainment",
		Website: "N/A",
		Response: "True",
		id: 170,
		tconst: "tt0111161",
		averageRating: 9.3,
		numVotes: 2333702,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Hababam Sinifi",
		Year: "1975",
		Rated: "N/A",
		Released: "01 Apr 1975",
		Runtime: "87 min",
		Genre: "Comedy, Drama",
		Director: "Ertem Egilmez",
		Writer: "Umur Bugay, Rifat Ilgaz (novel)",
		Actors: "Kemal Sunal, Münir Özkul, Halit Akçatepe, Tarik Akan",
		Plot:
			"Lazy, uneducated students share a very close bond. They live together in the dormitory, where they plan their latest pranks. When a new headmaster arrives, the students naturally try to overthrow him. A comic war of nitwits follows.",
		Language: "Turkish",
		Country: "Turkey",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BOWI4NGQ1M2YtNDM2Yi00YzAzLWJmZmYtMjkxZWMwNmM5Y2NhXkEyXkFqcGdeQXVyMjQ2OTI2MzU@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.3/10" }],
		Metascore: "N/A",
		imdbRating: "9.3",
		imdbVotes: "37,089",
		imdbID: "tt0252487",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 242,
		tconst: "tt0252487",
		averageRating: 9.3,
		numVotes: 37139,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "The Godfather",
		Year: "1972",
		Rated: "R",
		Released: "24 Mar 1972",
		Runtime: "175 min",
		Genre: "Crime, Drama",
		Director: "Francis Ford Coppola",
		Writer:
			"Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)",
		Actors: "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
		Plot:
			"An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
		Language: "English, Italian, Latin",
		Country: "USA",
		Awards: "Won 3 Oscars. Another 26 wins & 30 nominations.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.2/10" },
			{ Source: "Rotten Tomatoes", Value: "98%" },
			{ Source: "Metacritic", Value: "100/100" },
		],
		Metascore: "100",
		imdbRating: "9.2",
		imdbVotes: "1,612,983",
		imdbID: "tt0068646",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "$134,966,411",
		Production: "Paramount Pictures",
		Website: "N/A",
		Response: "True",
		id: 79,
		tconst: "tt0068646",
		averageRating: 9.2,
		numVotes: 1613300,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "CM101MMXI Fundamentals",
		Year: "2013",
		Rated: "N/A",
		Released: "03 Jan 2013",
		Runtime: "139 min",
		Genre: "Documentary, Comedy",
		Director: "Murat Dündar",
		Writer: "Cem Yilmaz",
		Actors: "Cem Yilmaz",
		Plot:
			"The funny little details of everyday life; the simple things that makes us laugh. An unforgettable performance from Cem Yilmaz. Yilmaz captures the audience with his hilarious stories about...",
		Language: "Turkish",
		Country: "Turkey",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMjE0Njc3MDQ5MV5BMl5BanBnXkFtZTcwNzIwNTQ5OA@@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.2/10" }],
		Metascore: "N/A",
		imdbRating: "9.2",
		imdbVotes: "43,810",
		imdbID: "tt2592910",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 396,
		tconst: "tt2592910",
		averageRating: 9.2,
		numVotes: 43865,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title:
			"Hare Krishna! The Mantra, the Movement and the Swami Who Started It All",
		Year: "2017",
		Rated: "N/A",
		Released: "03 Jun 2017",
		Runtime: "90 min",
		Genre: "Documentary",
		Director:
			"John Griesser, Jean Griesser(co-director), Lauren Ross(co-director)",
		Writer: "Mukunda Michael Dewil, Jean Griesser",
		Actors: "Sally Agarwal, Boy George, Edwin Bryant, Gaura Vani Buchwald",
		Plot:
			'"Hare Krishna!" is a documentary on the life of Srila Prabhupada, the 70-year-old Indian Swami who arrives in America without support or money and ignites a worldwide spiritual phenomenon, now known as the Hare Krishna Movement.',
		Language: "English",
		Country: "USA",
		Awards: "N/A",
		Poster:
			"https://ia.media-imdb.com/images/M/MV5BZmZmZjUwYjUtYWY5My00MjAyLWI4MDAtZDdlZDQ4ZTllYzQ0XkEyXkFqcGdeQXVyNTkwMjA4MzA@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.8/10" },
			{ Source: "Rotten Tomatoes", Value: "20%" },
			{ Source: "Metacritic", Value: "41/100" },
		],
		Metascore: "41",
		imdbRating: "9.8",
		imdbVotes: "736",
		imdbID: "tt6842524",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 478,
		tconst: "tt6842524",
		averageRating: 9.2,
		numVotes: 1325,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Aguner Poroshmoni",
		Year: "1994",
		Rated: "N/A",
		Released: "16 Dec 1994",
		Runtime: "123 min",
		Genre: "Drama, War",
		Director: "Humayun Ahmed",
		Writer:
			"Humayun Ahmed (novel), Humayun Ahmed (dialogue), Humayun Ahmed (screenplay)",
		Actors: "Bipasha Hayat, Asaduzzaman Noor, Abul Hayat, Dolly Johur",
		Plot:
			"In the middle of the 1971;curfew is going on all over the Bangladesh. The liberation army is operated as effective guerrilla force - Badiul Alam is one them. Alam plans for starting ...",
		Language: "Bengali",
		Country: "Bangladesh",
		Awards: "8 wins.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BZTgxNzE4ZTQtNzRhOS00YmJjLWExY2YtNGU5OGUyMTEzNTI5XkEyXkFqcGdeQXVyNjA3OTI5MjA@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.1/10" },
			{ Source: "Rotten Tomatoes", Value: "96%" },
		],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "2,177",
		imdbID: "tt0383177",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 295,
		tconst: "tt0383177",
		averageRating: 9.1,
		numVotes: 2749,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Love on a Leash",
		Year: "2011",
		Rated: "Not Rated",
		Released: "N/A",
		Runtime: "90 min",
		Genre: "Comedy, Drama, Fantasy, Romance",
		Director: "Fen Tian",
		Writer: "Fen Tian (screenplay)",
		Actors: "Gloria Winship Ayon, Shane Ayon, Jana Camp, Aneese Khamo",
		Plot:
			"Love takes a furry twist in this slice of romantic comedy. A young woman falls for a stray dog with a secret: by night, it becomes a man. Follow the journey of the golden retriever and the friend who gives him a home.",
		Language: "N/A",
		Country: "USA",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BODE2NDQ0OTY1MV5BMl5BanBnXkFtZTgwMjIxMjg5NTE@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.5/10" },
			{ Source: "Rotten Tomatoes", Value: "97%" },
		],
		Metascore: "N/A",
		imdbRating: "9.5",
		imdbVotes: "5,816",
		imdbID: "tt2185022",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "Fenix Pictures, Indie Crush",
		Website: "N/A",
		Response: "True",
		id: 384,
		tconst: "tt2185022",
		averageRating: 9.1,
		numVotes: 6785,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Aynabaji",
		Year: "2016",
		Rated: "N/A",
		Released: "30 Sep 2016",
		Runtime: "147 min",
		Genre: "Crime, Mystery, Thriller",
		Director: "Amitabh Reza Chowdhury",
		Writer:
			"Syed Gaosul Alam Shaon (story), Anam Biswas (dialogue), Adnan Adib Khan (dialogue), Anam Biswas (screenplay), Syed Gaosul Alam Shaon (screenplay)",
		Actors:
			"Chanchal Chowdhury, Masuma Rahman Nabila, Bijori Barkatullah, Partho Barua",
		Plot:
			"Ayna is an actor and the prison is his stage. He slips into the characters of the powerful convicted in exchange of money and take their place in prison. This strange profession is borne ...",
		Language: "Bengali",
		Country: "Bangladesh",
		Awards: "7 wins.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMmVmYWFkYWMtOThhZC00Y2VkLTkyNjMtYTBkNmE2ZTNlNmQzXkEyXkFqcGdeQXVyNjMxNjgwOTk@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.1/10" }],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "19,416",
		imdbID: "tt5354160",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 448,
		tconst: "tt5354160",
		averageRating: 9.1,
		numVotes: 22950,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Dominion",
		Year: "2018",
		Rated: "N/A",
		Released: "10 Jun 2018",
		Runtime: "120 min",
		Genre: "Documentary",
		Director: "Chris Delforce",
		Writer: "Chris Delforce",
		Actors: "Joaquin Phoenix, Rooney Mara, Sia, Sadie Sink",
		Plot:
			"Dominion uses drones, hidden and handheld cameras to expose the dark underbelly of modern animal agriculture, questioning the morality and validity of humankind's dominion over the animal kingdom.",
		Language: "English",
		Country: "Australia",
		Awards: "15 wins.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BOWMyNzExNzctOWNjNy00MzMxLWJlYWMtYjJiYmM0Mjg0YWZmXkEyXkFqcGdeQXVyNTU5NjAwMTQ@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.1/10" }],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "2,270",
		imdbID: "tt5773402",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 455,
		tconst: "tt5773402",
		averageRating: 9.1,
		numVotes: 2469,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "The Transcendents",
		Year: "2018",
		Rated: "Not Rated",
		Released: "19 Jun 2020",
		Runtime: "96 min",
		Genre: "Music, Mystery, Thriller",
		Director: "Derek Ahonen",
		Writer: "Derek Ahonen",
		Actors: "Rob Franco, Savannah Welch, Kathy Valentine, William Leroy",
		Plot:
			"Roger, a Rasputin-like drifter, is in search of the ultimate indie-rock band, The Transcendents. What he finds is less than transcendent: a band who has all but abandoned society, a host of...",
		Language: "English",
		Country: "USA",
		Awards: "8 wins & 10 nominations.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BNmU3MjUxZTQtNTA1NS00OGFiLWE0NmEtY2NhODg2MzgzMTM2XkEyXkFqcGdeQXVyMTQ2OTU2OTQ@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.1/10" }],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "1,466",
		imdbID: "tt5980638",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "$2,041",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 463,
		tconst: "tt5980638",
		averageRating: 9.1,
		numVotes: 1467,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Maya Bazaar",
		Year: "1957",
		Rated: "Not Rated",
		Released: "27 Mar 1957",
		Runtime: "192 min",
		Genre: "Comedy, Drama, Family, Musical",
		Director: "Kadiri Venkata Reddy",
		Writer:
			"Aluri Chakrapani (screen adaptation), Pingali Nagendra Rao (dialogue), Pingali Nagendra Rao (screen adaptation), Kadiri Venkata Reddy (adaptation)",
		Actors:
			"Taraka Rama Rao Nandamuri, S.V. Ranga Rao, Savitri, Gemini Ganesan",
		Plot:
			"Balarama promises Subhadra to get his daughter married to her son. But when the Pandavas loses their kingdom to the Kaurava's, Balarama breaks his promise.",
		Language: "Telugu, Tamil",
		Country: "India",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMmQwNjExNzctMGE1NC00NGU2LWEwN2ItMzljZmU4ODk5ZGRmXkEyXkFqcGdeQXVyMzA0NTI2OTM@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.1/10" }],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "4,025",
		imdbID: "tt0249795",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 239,
		tconst: "tt0249795",
		averageRating: 9.1,
		numVotes: 4022,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Little Baby",
		Year: "2019",
		Rated: "N/A",
		Released: "27 Sep 2019",
		Runtime: "105 min",
		Genre: "Family",
		Director: "Shekhar S. Jha",
		Writer: "Rashid Iqbal, Shekhar S. Jha, Siddharth Saigal",
		Actors:
			"Priyanshu Chatterjee, Gulnaz Siganporia, Sunnyy Balloria, Badrish Chhabra",
		Plot:
			"Little Baby is a story of unconditional love between a father and daughter. Sasha is a 19 year old girl who loves to experiment with her life and in this, she forgets she has a loving father and a mother.",
		Language: "Hindi",
		Country: "India",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BNDY2MzE3MmEtOWNjOS00MDY0LThkZDAtZDRiMjQ5ODNkNGI5XkEyXkFqcGdeQXVyNTc0MjY0NTM@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.1/10" }],
		Metascore: "N/A",
		imdbRating: "9.1",
		imdbVotes: "2,092",
		imdbID: "tt8569206",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 503,
		tconst: "tt8569206",
		averageRating: 9.1,
		numVotes: 2101,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Ramayana: The Legend of Prince Rama",
		Year: "1992",
		Rated: "PG",
		Released: "10 May 1992",
		Runtime: "170 min",
		Genre: "Animation, Action, Adventure, Drama, Fantasy, Musical, Romance",
		Director: "Ram Mohan, Yûgô Sakô, Koichi Saski",
		Writer: "Krishna Shah, Valmiki (story)",
		Actors: "Bryan Cranston, Arun Govil, Srija, Edie Mirman",
		Plot:
			"An anime adaptation of the Hindu myth the Ramayana, where the avatar Sri Ram combats the wicked king Ravana.",
		Language: "English",
		Country: "India, Japan",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMjI0YzhlNjYtMGFhZS00ZDI3LTg4NDQtNTNmNjM2NzNkY2RhXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "8.7/10" },
			{ Source: "Rotten Tomatoes", Value: "70%" },
		],
		Metascore: "N/A",
		imdbRating: "8.7",
		imdbVotes: "1,337",
		imdbID: "tt0259534",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "MRI Inc.",
		Website: "N/A",
		Response: "True",
		id: 257,
		tconst: "tt0259534",
		averageRating: 9,
		numVotes: 2157,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Uncle Tom",
		Year: "2020",
		Rated: "G",
		Released: "19 Jun 2020",
		Runtime: "106 min",
		Genre: "Documentary",
		Director: "Justin Malone",
		Writer: "Ryder Ansell, Larry Elder, Justin Malone",
		Actors: "Chad Jackson, Brandon Tatum, Candace Owens, Larry Elder",
		Plot: "An oral history of the American black conservative.",
		Language: "English",
		Country: "USA",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BYjUxN2NmMTUtMGE5YS00MzM4LWI1MmUtMTQ1ZGFmYjYzZDJhXkEyXkFqcGdeQXVyNjA0MjgwMzc@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.0/10" }],
		Metascore: "N/A",
		imdbRating: "9.0",
		imdbVotes: "4,747",
		imdbID: "tt9708358",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 516,
		tconst: "tt9708358",
		averageRating: 9,
		numVotes: 4773,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Opasen char",
		Year: "1984",
		Rated: "N/A",
		Released: "18 Jun 1984",
		Runtime: "90 min",
		Genre: "Comedy, Thriller",
		Director: "Ivan Andonov",
		Writer: "Svoboda Bachvarova",
		Actors: "Todor Kolev, Nevena Kokanova, Stefan Mavrodiyev, Lyuben Chatalov",
		Plot:
			"He is well educated, charming, and gallant - a dream for each lonely lady. In reality he is a skillful swindler, who robs naive women. Cheating merchants with guilty consciences are his ...",
		Language: "Bulgarian",
		Country: "Bulgaria",
		Awards: "N/A",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BNTUxMjAzNDI5NV5BMl5BanBnXkFtZTgwNDI0MDQxNjE@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.0/10" }],
		Metascore: "N/A",
		imdbRating: "9.0",
		imdbVotes: "1,580",
		imdbID: "tt0283524",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 267,
		tconst: "tt0283524",
		averageRating: 9,
		numVotes: 1626,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "12 Angry Men",
		Year: "1957",
		Rated: "Approved",
		Released: "10 Apr 1957",
		Runtime: "96 min",
		Genre: "Crime, Drama",
		Director: "Sidney Lumet",
		Writer: "Reginald Rose (story), Reginald Rose (screenplay)",
		Actors: "Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall",
		Plot:
			"A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
		Language: "English",
		Country: "USA",
		Awards: "Nominated for 3 Oscars. Another 17 wins & 10 nominations.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.0/10" },
			{ Source: "Rotten Tomatoes", Value: "100%" },
			{ Source: "Metacritic", Value: "96/100" },
		],
		Metascore: "96",
		imdbRating: "9.0",
		imdbVotes: "682,907",
		imdbID: "tt0050083",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "Orion-Nova Pictures",
		Website: "N/A",
		Response: "True",
		id: 28,
		tconst: "tt0050083",
		averageRating: 9,
		numVotes: 686925,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "Sandesham",
		Year: "1991",
		Rated: "Not Rated",
		Released: "30 Oct 1991",
		Runtime: "138 min",
		Genre: "Comedy, Drama",
		Director: "Sathyan Anthikad",
		Writer: "Sreenivasan",
		Actors: "Sreenivasan, Jayaram, Thilakan, Mathu",
		Plot:
			"A satire on contemporary Kerala politics where brothers turn local leaders of rival parties, leading to distress for their aged and once-proud parents.",
		Language: "Malayalam",
		Country: "India",
		Awards: "1 win.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BZDcwNGQ1NTctZjNkZC00ODJmLWE0NWQtMzc3YzhlNmI1OGQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_SX300.jpg",
		Ratings: [{ Source: "Internet Movie Database", Value: "9.0/10" }],
		Metascore: "N/A",
		imdbRating: "9.0",
		imdbVotes: "2,849",
		imdbID: "tt0353975",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "N/A",
		Production: "N/A",
		Website: "N/A",
		Response: "True",
		id: 284,
		tconst: "tt0353975",
		averageRating: 9,
		numVotes: 3564,
		created: "2021-01-16T19:48:55.000Z",
	},
	{
		Title: "The Dark Knight",
		Year: "2008",
		Rated: "PG-13",
		Released: "18 Jul 2008",
		Runtime: "152 min",
		Genre: "Action, Crime, Drama, Thriller",
		Director: "Christopher Nolan",
		Writer:
			"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)",
		Actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
		Plot:
			"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
		Language: "English, Mandarin",
		Country: "USA, UK",
		Awards: "Won 2 Oscars. Another 156 wins & 163 nominations.",
		Poster:
			"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
		Ratings: [
			{ Source: "Internet Movie Database", Value: "9.0/10" },
			{ Source: "Rotten Tomatoes", Value: "94%" },
			{ Source: "Metacritic", Value: "84/100" },
		],
		Metascore: "84",
		imdbRating: "9.0",
		imdbVotes: "2,294,527",
		imdbID: "tt0468569",
		Type: "movie",
		DVD: "N/A",
		BoxOffice: "$534,858,444",
		Production: "Syncopy",
		Website: "N/A",
		Response: "True",
		id: 308,
		tconst: "tt0468569",
		averageRating: 9,
		numVotes: 2294915,
		created: "2021-01-16T19:48:55.000Z",
	},
];
module.exports = testData